"""Shared OpenPGP contracts and trusted secret-source API."""

from .contracts import (
    ENVELOPE_FORMAT,
    ENVELOPE_SCHEMA_VERSION,
    ContractErrorCode,
    EnvelopeHeader,
    EnvelopePolicy,
    KeyCapability,
    KeyProfile,
    LocalTrust,
    OpenPGPContractError,
    RSA_4096_TWO_YEAR_PROFILE,
    TrustAssessment,
    assess_signer_trust,
    expected_expiry_date,
    normalize_fingerprint,
    require_capabilities,
    validate_envelope_header,
    validate_envelope_participants,
    validate_key_profile,
)
from .secrets import (
    SecretProvider,
    SecretReference,
    SecretResolutionError,
    SecretResolutionErrorCode,
    SecretResolver,
)


__all__ = [
    "ENVELOPE_FORMAT",
    "ENVELOPE_SCHEMA_VERSION",
    "ContractErrorCode",
    "EnvelopeHeader",
    "EnvelopePolicy",
    "KeyCapability",
    "KeyProfile",
    "LocalTrust",
    "OpenPGPContractError",
    "RSA_4096_TWO_YEAR_PROFILE",
    "TrustAssessment",
    "assess_signer_trust",
    "expected_expiry_date",
    "normalize_fingerprint",
    "require_capabilities",
    "validate_envelope_header",
    "validate_envelope_participants",
    "validate_key_profile",
    "SecretProvider",
    "SecretReference",
    "SecretResolutionError",
    "SecretResolutionErrorCode",
    "SecretResolver",
]
