"""Shared OpenPGP contracts, key lifecycle, and secret-source APIs."""

from .contracts import (
    ENVELOPE_FORMAT,
    ENVELOPE_SCHEMA_VERSION,
    ContractErrorCode,
    EnvelopeHeader,
    EnvelopePolicy,
    KeyCapability,
    KeyProfile,
    LocalTrust,
    OpenPGPContractError,
    RSA_4096_TWO_YEAR_PROFILE,
    TrustAssessment,
    assess_signer_trust,
    expected_expiry_date,
    normalize_fingerprint,
    require_capabilities,
    validate_envelope_header,
    validate_envelope_participants,
    validate_key_profile,
)
from .secrets import (
    SecretProvider,
    SecretReference,
    SecretResolutionError,
    SecretResolutionErrorCode,
    SecretResolver,
)
from .keys import (
    KeyEnrollment,
    KeyInspection,
    KeyInspectionError,
    KeyInspectionErrorCode,
    KeyRecord,
    enroll_key,
    inspect_key,
)
from .discovery import (
    CertificateDiscoveryResult,
    CertificateDiscoveryStatus,
    discover_github_certificate,
)
from .generation import (
    GeneratedKey,
    KeyGenerationError,
    KeyGenerationErrorCode,
    KeyIdentity,
    generate_key,
)
from .envelope import EnvelopeError, EnvelopeErrorCode, seal_envelope
from .opening import EnvelopeOpenError, EnvelopeOpenErrorCode, open_envelope
from .historical import open_historical_envelope
from .recovery import (
    ProtectedBackup,
    RecoveredKey,
    RecoveryError,
    RecoveryErrorCode,
    create_protected_backup,
    restore_protected_backup,
)
from .transition import (
    ApprovedTransitionRecord,
    TransitionError,
    TransitionErrorCode,
    TransitionProposal,
    VerifiedTransition,
    approve_transition_proposal,
    create_transition_proposal,
    encrypt_transition_proposal,
    verify_approved_transition,
)

from .publishing_transition import (
    ApprovedPublishingTransitionRecord,
    PublishingTransitionProof,
    PublishingTransitionProposal,
    VerifiedPublishingTransition,
    approve_publishing_transition,
    create_publishing_transition_proposal,
    sign_publishing_transition_proposal,
    verify_approved_publishing_transition,
)

from .trust_state import (
    Authority,
    TrustSnapshot,
    TrustStateError,
    initialize_trust_state,
    load_trust_state,
    apply_owner_transition,
    apply_publisher_transition,
    authorize_outbound,
    authorize_inbound_peer,
    record_accepted_content,
    authorize_historical_content,
    revoke_authority,
)
from .recovery_transition import (
    RecoveryChallenge,
    LocalRecoveryReceipt,
    create_recovery_challenge,
    sign_recovery_challenge,
    submit_candidate_proof,
    authorize_recovery_locally,
    enroll_recovery_key,
    apply_recovery_transition,
)


__all__ = [
    "ENVELOPE_FORMAT",
    "ENVELOPE_SCHEMA_VERSION",
    "ContractErrorCode",
    "EnvelopeHeader",
    "EnvelopePolicy",
    "KeyCapability",
    "KeyProfile",
    "LocalTrust",
    "OpenPGPContractError",
    "RSA_4096_TWO_YEAR_PROFILE",
    "TrustAssessment",
    "assess_signer_trust",
    "expected_expiry_date",
    "normalize_fingerprint",
    "require_capabilities",
    "validate_envelope_header",
    "validate_envelope_participants",
    "validate_key_profile",
    "KeyEnrollment",
    "KeyInspection",
    "KeyInspectionError",
    "KeyInspectionErrorCode",
    "KeyRecord",
    "enroll_key",
    "inspect_key",
    "CertificateDiscoveryResult",
    "CertificateDiscoveryStatus",
    "discover_github_certificate",
    "GeneratedKey",
    "KeyGenerationError",
    "KeyGenerationErrorCode",
    "KeyIdentity",
    "generate_key",
    "EnvelopeError",
    "EnvelopeErrorCode",
    "seal_envelope",
    "EnvelopeOpenError",
    "EnvelopeOpenErrorCode",
    "open_envelope",
    "open_historical_envelope",
    "ProtectedBackup",
    "RecoveredKey",
    "RecoveryError",
    "RecoveryErrorCode",
    "create_protected_backup",
    "restore_protected_backup",
    "ApprovedTransitionRecord",
    "TransitionError",
    "TransitionErrorCode",
    "TransitionProposal",
    "VerifiedTransition",
    "approve_transition_proposal",
    "create_transition_proposal",
    "encrypt_transition_proposal",
    "verify_approved_transition",
    "ApprovedPublishingTransitionRecord",
    "PublishingTransitionProof",
    "PublishingTransitionProposal",
    "VerifiedPublishingTransition",
    "approve_publishing_transition",
    "create_publishing_transition_proposal",
    "sign_publishing_transition_proposal",
    "verify_approved_publishing_transition",
    "Authority",
    "TrustSnapshot",
    "TrustStateError",
    "initialize_trust_state",
    "load_trust_state",
    "apply_owner_transition",
    "apply_publisher_transition",
    "authorize_outbound",
    "authorize_inbound_peer",
    "record_accepted_content",
    "authorize_historical_content",
    "revoke_authority",
    "RecoveryChallenge",
    "LocalRecoveryReceipt",
    "create_recovery_challenge",
    "sign_recovery_challenge",
    "submit_candidate_proof",
    "authorize_recovery_locally",
    "enroll_recovery_key",
    "apply_recovery_transition",
    "SecretProvider",
    "SecretReference",
    "SecretResolutionError",
    "SecretResolutionErrorCode",
    "SecretResolver",
]
