from __future__ import annotations

import argparse

from .framework_version import framework_version
from .repo_profiles import REPO_PROFILES


def build_parser(add_config_flags, add_selector_flags, add_visual_flags, add_harness_target_flags) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="localsetup")
    parser.add_argument("-V", "--version", action="version", version=f"%(prog)s {framework_version()}")
    parser.add_argument("--home")
    parser.add_argument("--source-root")
    parser.add_argument("--repo", default=None, help=argparse.SUPPRESS)
    parser.add_argument("--target-directory")
    sub = parser.add_subparsers(dest="cmd")

    plan_p = sub.add_parser("plan")
    add_config_flags(plan_p)
    add_selector_flags(plan_p)

    install_p = sub.add_parser("install")
    add_config_flags(install_p, include_apply=True)
    add_selector_flags(install_p)

    verify_p = sub.add_parser("verify")
    add_config_flags(verify_p)
    verify_p.add_argument("--platforms", "--tools", nargs="*", dest="platforms")
    verify_p.add_argument("--level", choices=["filesystem"], default="filesystem")

    rollback_p = sub.add_parser("rollback")
    add_config_flags(rollback_p)
    rollback_p.add_argument("--platforms", "--tools", nargs="*", dest="platforms")

    update_p = sub.add_parser("update")
    add_config_flags(update_p)
    add_selector_flags(update_p)

    adapters_p = sub.add_parser("adapters")
    adapters_p.add_argument("--target-directory", default=argparse.SUPPRESS)
    adapters_p.add_argument("--platforms", "--tools", nargs="*", dest="platforms")
    adapters_p.add_argument("--json", action="store_true", help=argparse.SUPPRESS)
    adapters_p.add_argument("--provenance", action="store_true")
    adapters_sub = adapters_p.add_subparsers(dest="adapter_action")
    adapters_check_p = adapters_sub.add_parser("check")
    adapters_check_p.add_argument("--target-directory", default=argparse.SUPPRESS)
    adapters_check_p.add_argument("--platforms", "--tools", nargs="*", dest="platforms")
    adapters_check_p.add_argument("--json", action="store_true", help=argparse.SUPPRESS)
    adapters_check_p.add_argument("--provenance", action="store_true")
    configure_p = sub.add_parser("configure")
    add_config_flags(configure_p)
    add_selector_flags(configure_p)
    configure_p.add_argument("--home-override")

    doctor_p = sub.add_parser("doctor")
    add_config_flags(doctor_p)
    add_selector_flags(doctor_p)
    doctor_p.add_argument("--provenance", action="store_true")
    doctor_sub = doctor_p.add_subparsers(dest="doctor_action")
    doctor_repair_p = doctor_sub.add_parser("repair")
    add_config_flags(doctor_repair_p)
    doctor_repair_p.add_argument("--yes", action="store_true", dest="apply")
    doctor_repair_p.add_argument("--platforms", "--tools", nargs="*", dest="platforms")
    doctor_repair_p.add_argument(
        "--repair-mode",
        choices=["report-only", "safe-repair", "migration-plan", "apply-with-backups"],
        default=None,
    )
    doctor_repair_p.add_argument("--allow", action="append", default=[])
    doctor_repair_p.add_argument("--agent-prompt", action="store_true")
    doctor_repair_p.add_argument("--emit-agent-prompt")

    migrate_p = sub.add_parser("migrate")
    add_config_flags(migrate_p)
    migrate_p.add_argument("--platforms", "--tools", nargs="*", dest="platforms")
    migrate_p.add_argument("--dry-run", action="store_true")

    context_p = sub.add_parser("context")
    add_config_flags(context_p)
    add_selector_flags(context_p)
    context_p.add_argument("--markdown", action="store_true", default=None)

    convert_p = sub.add_parser("convert")
    add_config_flags(convert_p, include_apply=True)
    add_selector_flags(convert_p)

    sub.add_parser("catalog")
    diff_p = sub.add_parser("diff")
    add_config_flags(diff_p)
    add_selector_flags(diff_p)
    skill_p = sub.add_parser("skill")
    skill_sub = skill_p.add_subparsers(dest="skill_action", required=True)
    skill_search = skill_sub.add_parser("search")
    skill_search.add_argument("query", nargs="?")
    skill_info = skill_sub.add_parser("info")
    skill_info.add_argument("query")
    candidate_skill_p = sub.add_parser("candidate-skill")
    candidate_skill_sub = candidate_skill_p.add_subparsers(dest="candidate_skill_action", required=True)
    candidate_validate = candidate_skill_sub.add_parser("validate")
    candidate_validate.add_argument("--candidate", required=True)
    candidate_validate.add_argument("--json", action="store_true", help=argparse.SUPPRESS)
    candidate_proposal = candidate_skill_sub.add_parser("proposal")
    candidate_proposal.add_argument("--candidate", required=True)
    candidate_proposal.add_argument("--output", default="-")
    workflow_p = sub.add_parser("workflow")
    workflow_sub = workflow_p.add_subparsers(dest="workflow_action", required=True)
    workflow_search = workflow_sub.add_parser("search")
    workflow_search.add_argument("query", nargs="?")
    workflow_info = workflow_sub.add_parser("info")
    workflow_info.add_argument("query")
    why_p = sub.add_parser("why")
    why_p.add_argument("--packs", nargs="*")
    sub.add_parser("graph")
    path_p = sub.add_parser("path")
    path_p.add_argument("--json", action="store_true", help="Emit all Localsetup resolved paths as JSON")
    path_sub = path_p.add_subparsers(dest="path_action")
    path_sub.add_parser("source-root")
    path_sub.add_parser("framework-root")
    path_sub.add_parser("docs-root")
    path_sub.add_parser("tools-root")
    path_sub.add_parser("package-root")
    path_package = path_sub.add_parser("package")
    path_package.add_argument("name")
    path_package.add_argument("relative_path", nargs="?")
    path_doc = path_sub.add_parser("doc")
    path_doc.add_argument("relative_path")
    path_tool = path_sub.add_parser("tool")
    path_tool.add_argument("relative_path")
    adopt_p = sub.add_parser("adopt")
    adopt_p.add_argument("--target-directory", default=argparse.SUPPRESS)
    detach_p = sub.add_parser("detach")
    add_config_flags(detach_p)
    detach_p.add_argument("--platforms", "--tools", nargs="*", dest="platforms", required=True)
    sbom_p = sub.add_parser("sbom")
    sbom_p.add_argument("--format", choices=["cyclonedx"], default="cyclonedx")
    sbom_p.add_argument("--out", required=True)
    sbom_p.add_argument("--installed", action="store_true")
    sbom_p.add_argument("--target-directory", default=argparse.SUPPRESS)
    scan_migration_p = sub.add_parser("scan-migration")
    scan_migration_p.add_argument("--include-expected", action="store_true")
    reprocess_paths_p = sub.add_parser("reprocess-paths")
    reprocess_paths_p.add_argument("--apply", action="store_true", help="Reserved for future allowlisted rewrites; currently rejected for safety")
    sub.add_parser("validate-package-surface")
    test_workers_p = sub.add_parser("test-workers")
    test_workers_p.add_argument("--workers", help="Optional numeric override; clamped to the host-effective 1..8 limit")
    test_workers_p.add_argument("--json", action="store_true", help="Emit worker calculation details")
    audit_global_p = sub.add_parser("audit-global-first")
    audit_global_p.add_argument("--target-directory", default=argparse.SUPPRESS)
    sub.add_parser("validate-catalog")
    sub.add_parser("generate-docs")
    client_registry_p = sub.add_parser("client-registry")
    client_registry_sub = client_registry_p.add_subparsers(dest="client_registry_action", required=True)
    client_registry_sub.add_parser("check")
    client_registry_sub.add_parser("generate")
    client_registry_drift_p = client_registry_sub.add_parser("drift")
    client_registry_drift_p.add_argument("--left", required=True, help="Canonical family/variant key")
    client_registry_drift_p.add_argument("--right", required=True, help="Canonical family/variant key")
    state_p = sub.add_parser("state")
    state_sub = state_p.add_subparsers(dest="state_action", required=True)
    for state_action in ("path", "allocate"):
        state_action_p = state_sub.add_parser(state_action)
        state_action_p.add_argument("--client", required=True, help="Canonical family/variant key")
        state_action_p.add_argument("--scope", choices=["auto", "repo", "global"], default="auto")
        state_action_p.add_argument("--directory", default=None, help="Directory used for Git worktree detection")
        state_action_p.add_argument("--child", help="Validated state child; requires an explicit repo or global scope")
    state_path_p = state_sub.choices["path"]
    state_path_p.add_argument("--apply-exclude", action="store_true")
    state_allocate_p = state_sub.choices["allocate"]
    state_allocate_p.add_argument("--agent")
    state_allocate_p.add_argument("--purpose", required=True)
    state_allocate_p.add_argument("--extension", required=True)
    state_allocate_p.add_argument("--kind", required=True)
    state_allocate_p.add_argument("--schema", required=True)
    state_allocate_p.add_argument("--producer", required=True)
    state_allocate_p.add_argument("--consumer", action="append", default=[])
    state_allocate_p.add_argument("--predecessor")
    state_allocate_p.add_argument("--checkpoint")
    state_allocate_p.add_argument("--content-file")
    state_verify_p = state_sub.add_parser("verify")
    state_verify_p.add_argument("--client", required=True, help="Canonical family/variant key")
    state_verify_p.add_argument("--scope", choices=["auto", "repo", "global"], default="auto")
    state_verify_p.add_argument("--directory", default=None, help="Directory used for Git worktree detection")
    state_verify_p.add_argument("--child", help="Validated state child; requires an explicit repo or global scope")
    state_verify_p.add_argument("--artifact", required=True, help="Direct-child artifact filename")
    state_telemetry_p = state_sub.add_parser("telemetry")
    state_telemetry_p.add_argument("--client", required=True, help="Canonical family/variant key")
    state_telemetry_p.add_argument("--scope", choices=["repo", "global"], required=True)
    state_telemetry_p.add_argument("--directory", default=None, help="Directory used for Git worktree detection")
    provenance_p = sub.add_parser("provenance")
    provenance_sub = provenance_p.add_subparsers(dest="provenance_action", required=True)
    provenance_report_p = provenance_sub.add_parser("report")
    add_config_flags(provenance_report_p)
    provenance_report_p.add_argument("--platforms", "--tools", nargs="*", dest="platforms")
    repair_p = provenance_sub.add_parser("repair")
    repair_p.add_argument("--plan", action="store_true", required=True)
    health_p = sub.add_parser("health")
    health_p.add_argument("--json", action="store_true", help=argparse.SUPPRESS)
    health_p.add_argument("--target-directory", default=argparse.SUPPRESS)
    health_sub = health_p.add_subparsers(dest="health_action")
    health_queue = health_sub.add_parser("repair-queue")
    health_queue.add_argument("--json", action="store_true", help=argparse.SUPPRESS)
    health_queue.add_argument("--agent-prompts")
    harness_p = sub.add_parser("harness")
    harness_sub = harness_p.add_subparsers(dest="harness_topic", required=True)
    heartbeat_p = harness_sub.add_parser("codex-heartbeat")
    heartbeat_sub = heartbeat_p.add_subparsers(dest="harness_action", required=True)
    for action_name in ("plan", "init", "status", "budget"):
        action_p = heartbeat_sub.add_parser(action_name)
        add_harness_target_flags(action_p)
    for action_name in ("enable", "disable"):
        action_p = heartbeat_sub.add_parser(action_name)
        add_harness_target_flags(action_p)
        action_p.add_argument("--install-crontab", action="store_true")
        action_p.add_argument("--yes", action="store_true")
    run_p = heartbeat_sub.add_parser("run")
    add_harness_target_flags(run_p)
    run_p.add_argument("--no-agent", action="store_true")
    run_p.add_argument("--force", action="store_true")
    finalizer_p = harness_sub.add_parser("repo-finalizer")
    finalizer_sub = finalizer_p.add_subparsers(dest="harness_action", required=True)
    for action_name in ("plan", "status"):
        action_p = finalizer_sub.add_parser(action_name)
        add_harness_target_flags(action_p)
        action_p.add_argument("--mode", choices=["source", "target"])
        action_p.add_argument("--json", action="store_true")
    finalizer_run_p = finalizer_sub.add_parser("run")
    add_harness_target_flags(finalizer_run_p)
    finalizer_run_p.add_argument("--mode", choices=["source", "target"])
    finalizer_run_p.add_argument("--json", action="store_true")
    finalizer_run_p.add_argument("--no-commit", action="store_true")
    finalizer_run_p.add_argument("--checkpoint", action="store_true")
    finalizer_run_p.add_argument("--message")
    docs_align_p = sub.add_parser("docs-align")
    docs_align_p.add_argument("docs_align_args", nargs=argparse.REMAINDER)

    plugin_p = sub.add_parser("plugin")
    plugin_sub = plugin_p.add_subparsers(dest="plugin_action", required=True)
    plugin_list_p = plugin_sub.add_parser("list")
    plugin_list_p.add_argument("--platform", choices=["codex"], default="codex")
    plugin_plan_p = plugin_sub.add_parser("plan")
    plugin_plan_p.add_argument("--platform", choices=["codex"], default="codex")
    plugin_plan_p.add_argument("--plugin-packs", nargs="*")
    plugin_plan_p.add_argument("--output")
    plugin_build_p = plugin_sub.add_parser("build")
    plugin_build_p.add_argument("--platform", choices=["codex"], default="codex")
    plugin_build_p.add_argument("--plugin-packs", nargs="*")
    plugin_build_p.add_argument("--output", required=True)
    plugin_validate_p = plugin_sub.add_parser("validate")
    plugin_validate_p.add_argument("--platform", choices=["codex"], default="codex")
    plugin_validate_p.add_argument("--path", required=True)

    context_index_p = sub.add_parser("context-index")
    context_index_p.add_argument("context_index_args", nargs=argparse.REMAINDER)

    domain_p = sub.add_parser("domain")
    domain_sub = domain_p.add_subparsers(dest="domain_action", required=True)
    domain_validate_p = domain_sub.add_parser("validate")
    domain_validate_p.add_argument("--config", required=True)
    domain_compile_p = domain_sub.add_parser("compile")
    domain_compile_p.add_argument("--config", required=True)
    domain_compile_p.add_argument("--domain", required=True)
    domain_compile_p.add_argument("--directory", required=True)

    hook_p = sub.add_parser("hook-gate")
    hook_p.add_argument("--out", default="/tmp/localsetup-public.tar.gz")
    hook_p.add_argument("--runner")

    version_plan_p = sub.add_parser("version-plan")
    version_plan_p.add_argument("--base")
    version_plan_p.add_argument("--head")
    version_plan_p.add_argument("--ref")
    version_plan_p.add_argument("--push-stdin", action="store_true")

    version_sync_p = sub.add_parser("version-sync")
    version_sync_p.add_argument("--base")
    version_sync_p.add_argument("--head")
    version_sync_p.add_argument("--target")
    version_sync_p.add_argument("--check", action="store_true")
    version_sync_p.add_argument("--stage", action="store_true")
    version_sync_p.add_argument("--commit", action="store_true")

    publish_preflight_p = sub.add_parser(
        "publish-preflight",
        help="Prepare an unstaged direct version-sync candidate, or commit it with --fix.",
        description=(
            "On a clean worktree, publish-preflight without --fix prepares an unstaged direct "
            "version-sync candidate for review. Use --fix to prepare and commit the required "
            "version and generated-document release slices."
        ),
    )
    publish_preflight_p.add_argument("--base")
    publish_preflight_p.add_argument("--head")
    publish_preflight_p.add_argument(
        "--fix",
        action="store_true",
        help="Prepare and commit the release version and generated-document sync slices.",
    )

    release_push_p = sub.add_parser("release-push")
    release_push_p.add_argument("push_args", nargs=argparse.REMAINDER)
    self_refresh_p = sub.add_parser("self-refresh")
    add_config_flags(self_refresh_p)
    add_selector_flags(self_refresh_p)

    sub.add_parser("install-hooks")
    sub.add_parser("register-shell")

    wizard_p = sub.add_parser("wizard")
    add_config_flags(wizard_p)
    add_selector_flags(wizard_p)
    wizard_p.add_argument("--repo-profile", choices=sorted(REPO_PROFILES))
    wizard_p.add_argument("--dry-run", action="store_true")
    wizard_p.add_argument("--apply", action="store_true")
    wizard_p.add_argument("--caller-directory")
    wizard_p.add_argument("--no-register-shell", action="store_true")
    wizard_p.add_argument("--target-directory-origin", choices=["explicit", "inferred"], default="explicit")
    add_visual_flags(wizard_p)

    package_p = sub.add_parser("package")
    package_p.add_argument("--out", default="dist/localsetup-public.tar.gz")
    verify_release_p = sub.add_parser("verify-release")
    verify_release_p.add_argument("artifact")
    verify_release_p.add_argument("--sha256")
    verify_release_p.add_argument("--sbom")
    verify_release_p.add_argument("--expected-commit")
    verify_release_p.add_argument("--expected-tag")

    return parser
